### ISSUE TITLE
Le makefile sous linux tourne en boucle ou plante

### ISSUE THREAD

**Issue by romulusFR** [ucacaxm/grapic#2]
make produit la liste infinie suivante
===========================

mkdir -p build ; cd build/linux ; make
/bin/sh: 1: cd: can't cd to build/linux
make[1]: Entering directory '/home/romulus/Documents/Enseignement/LIFAP1/TP/grapic'
mkdir -p build ; cd build/linux ; make
/bin/sh: 1: cd: can't cd to build/linux
make[2]: Entering directory '/home/romulus/Documents/Enseignement/LIFAP1/TP/grapic'

si on crée le dossier ./build/make, alors
===========================
mkdir -p build ; cd build/linux ; make
make[1]: Entering directory '/home/romulus/Documents/Enseignement/LIFAP1/TP/grapic/build/linux'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory '/home/romulus/Documents/Enseignement/LIFAP1/TP/grapic/build/linux'
Makefile:25: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by romulusFR** [comment]
make premake est ok par contre.

**Comment by ucacaxm** [comment]
La doc de Grapic n'est normalement pas pensé pour partir du github, il faut partir du .zip ou du .tgz telechargeable de la page web.

En partant du github, il faut faire d'abord make premake oui pour générer les makefiles, projet xcode, visual ou codeblocks.


je changerai la doc ou le makefile pour pouvoir partir du github ...






________________________________
De : Romuald Thion <notifications@github.com>
Envoyé : lundi 30 octobre 2017 10:50
À : ucacaxm/grapic
Cc : Subscribed
Objet : Re: [ucacaxm/grapic] Le makefile sous linux tourne en boucle ou plante (#2)


make premake est ok par contre.

-

**Comment by ucacaxm** [comment]
J'ai fait le changement dans le Makefile
